server:
  port: 8500
  servlet:
    context-path=/ps

# DB connection and hibernate properties
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/${DB_PROPERTY_DETAILS}
    username: ${DB_USERNAME}
    password: ${DB_PWD}
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
